#!/usr/bin/python
import facebook
import sys
messagefacebook=sys.argv[1]
graph = facebook.GraphAPI('CAAURY73RwKcBADffYrjhQ62MCA7rqkI6Wv2pnlU8ZBHn4XRKINQ4OU8RILIOABP9ZBMDwe9DyJnSnK8UaZBSJUHKQruIR5DP5JtiasOCkuGMAC5k7xkyr3xwLoWzDuHoZALZB567Avsq6PuFkE2a0FgRdNnXtVc82PF5gmZBBDKcDc3rzaaUquuepn9RJIwFDQcFs3IZCJi0wZDZD')
graph.put_object("me", "feed", message=messagefacebook)